Photovle/urls.py
from django.contrib import admin
from django.urls import include, path
from main import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # 관리자
    path('admin/', admin.site.urls),
    # 메인
    path('', include('main.urls')),
    # 로그인
    path('home/', include('allauth.urls')),
    # 비밀번호 초기화
    path('password_reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

main/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name='main'

urlpatterns = [
    # 메인페이지
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    # 로그인, 로그아웃
    path('home/login/', views.login, name='login'),
    path('home/logout/', views.logout, name='logout'),
    # 카카오 소셜로그인
    path('home/login/kakao/', views.kakao_login, name='kakao_login'),
    path('home/login/kakao/callback/', views.kakao_callback, name='kakao_callback'),
    # 회원가입
    path('home/signup/', views.signup, name='signup'),
    path('home/<int:pk>/addinfo/', views.addinfo, name='addinfo'),
    # 마이페이지
    path('home/mypage/', views.mypage, name='mypage'),
    path('home/update_user/', views.update_user, name='update_user'),
    path('home/delete_user/', views.delete_user, name='delete_user'),
    path('home/change_password/', views.change_password, name='change_password'),
    # 게시판
    path('board/', views.board, name='board'),
    path('board/<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/download/', views.download, name='download'),
    path('board/write/', views.write, name='write'),
    path('board/<int:pk>/update', views.update, name='update'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('mypost/', views.mypost, name='mypost'),
    # 댓글
    path('<int:pk>/create_reply', views.create_reply, name='create_reply'),
    path('<int:pk>/<int:rep_pk>/update_reply/', views.update_reply, name='update_reply'),
    path('<int:pk>/delete_reply', views.delete_reply, name='delete_reply'),
    # 작업Canvas
    path('osvos/', views.osvos, name='osvos'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import os
from django.db import models
from django.contrib.auth.models import AbstractUser
from Photovle import settings

# Create your models here.
# 장고유저 기반의 커스텀 유저모델
'''
장고에서 제공하는 auth를 확장하여 사용
phone : 유저의 전화번호(동일한 번호로 가입불가)
name : 유저의 이름
email : 유저의 이메일(동일한 이메일로 가입불가, 비밀번호초기화를 위해 입력받음)
'''
class User(AbstractUser):
    phone = models.CharField("전화번호", max_length=11, unique=True)
    name = models.CharField("이름", max_length=20)
    email = models.EmailField("이메일", max_length=200, unique=True)
    first_name = None
    last_name = None
    
    class Meta:
        db_table = 'user'

# 게시판 모델
'''
title : 게시글 제목
user : 게시글을 작성하는 유저
content : 게시글 내용
hits : 게시글의 조회수
pub_date : 게시글을 작성한 시간 or 수정한 시간
upload_files : 게시글에 첨부한 파일
'''
class Board(models.Model):
    title = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length=1000)
    hits = models.PositiveIntegerField(default=0)
    pub_date = models.DateTimeField()
    upload_files = models.FileField(upload_to="", null=True, blank=True)

    def __str__(self):
        return self.title

    @property
    def update_counter(self):
        self.hits = self.hits + 1
        self.save()
        
    def delete(self, *args, **kwargs):
        if self.upload_files:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.upload_files.path))
        super(Board, self).delete(*args, **kwargs)

# 댓글 모델
'''
board : 댓글이 달리는 board_id
user : 댓글을 다는 user_id
comment : 댓글내용
rep_date : 댓글을 작성한 시간 or 수정한 시간
'''
class Reply(models.Model):
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=400)
    rep_date = models.DateTimeField()

    def __str__(self):
        return self.comment

main/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django.forms import ModelForm
from django import forms
from .models import Board, Reply, User

# 유저 생성 form
class UserForm(UserCreationForm):
    name = forms.CharField(label='이름')
    email = forms.EmailField(label="이메일")
    phone = forms.CharField(label='전화번호')
    
    class Meta:
        model = User
        fields = ('name', 'username', 'password1', 'password2', 'email', 'phone')

# 소셜로그인 시 추가정보입력 form
class AddInfoForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('name', 'username', 'phone')

# 유저정보 수정 form
class UserUpdateForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('name', 'email', 'phone')

# 게시판 글쓰기 form
class BoardForm(ModelForm):
    class Meta:
        model = Board
        fields = ['title', 'content', 'upload_files']

# 게시판 댓글 form
class ReplyForm(ModelForm):
    class Meta:
        model = Reply
        fields = ['comment']

main/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import auth, messages
from django.contrib.auth import authenticate, update_session_auth_hash, login as dj_login
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm, AuthenticationForm
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect, FileResponse
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from Photovle import settings
from Photovle.settings import SOCIAL_OUTH_CONFIG
from .models import User, Board, Reply
from .forms import UserForm, AddInfoForm, UserUpdateForm, ReplyForm, BoardForm
import random
import string
import hashlib
import requests
import os

# Create your views here.
# 로고만 있는 인덱스 페이지
def index(request):
    return render(request, 'index.html')

# 메인페이지
def home(request):
    return render(request, 'home.html')

#######################회원관련################################
# 회원가입
def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            dj_login(request, user)
            return redirect('main:home')
    else:
        form = UserForm()
    context = {
        'form':form,
    }
    return render(request, 'signup.html', context)

# 로그인
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            dj_login(request, form.get_user())
            return redirect('main:home')
    else:
        # 로그인 된 유저의 경우 로그인 페이지 접근 불가
        if request.user.is_authenticated:
            return redirect('main:home')
        form = AuthenticationForm()
    context = {
        'form':form,
    }
    return render(request, 'login.html', context)

# 카카오 로그인
def kakao_login(request):
    client_id = SOCIAL_OUTH_CONFIG['KAKAO_REST_API_KEY']
    redirect_uri = SOCIAL_OUTH_CONFIG['KAKAO_REDIRECT_URI']
    url = f"https://kauth.kakao.com/oauth/authorize?response_type=code&client_id={client_id}&redirect_uri={redirect_uri}"
    return redirect(url)

def kakao_callback(request):
    code = request.GET.get('code')
    client_id = SOCIAL_OUTH_CONFIG['KAKAO_REST_API_KEY']
    redirect_uri = SOCIAL_OUTH_CONFIG['KAKAO_REDIRECT_URI']
    url = f'https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={client_id}&redirect_uri={redirect_uri}&code={code}'
    token_request = requests.post(url)
    token_json = token_request.json()
    access_token = token_json.get('access_token')
    profile_request = requests.post(
        'https://kapi.kakao.com/v2/user/me',
        headers={'Authorization':f'Bearer {access_token}'},
    )
    profile_json = profile_request.json()
    kakao_id = profile_json.get('id', None)
    account = profile_json.get('kakao_account')
    email = account.get('email', None)

    if User.objects.filter(email=email).exists():
        user = User.objects.get(email=email)
        if user.name=="" or user.phone=="":
            user.delete()
            return redirect('main:login')
        else:
            dj_login(request, user, 'django.contrib.auth.backends.ModelBackend')
            return redirect('main:home')
    else:
        # user 테이블에 넣기 위하여 임의의 password를 만들고 sha256으로 암호화
        tmp = string.ascii_letters + string.digits
        rs = ""
        for _ in range(12):
            rs += random.choice(tmp)
        print(rs)
        password = hashlib.sha256(rs.encode())
        kakao_account = User(
            username=kakao_id,
            email = email,
            password = password
        )
        kakao_account.save()
        user = User.objects.get(email=email)
        dj_login(request, user, 'django.contrib.auth.backends.ModelBackend')
        context = {
            'user':user,
        }
        return render(request, 'addinfo.html', context)

# 소셜로그인 시 추가정보 입력
def addinfo(request, pk):   # pk = user_id
    user = User.objects.get(id=pk)    
    if request.method == 'POST':
        form = AddInfoForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            dj_login(request, user, 'django.contrib.auth.backends.ModelBackend')
            return redirect('main:home')
        else:
            user.delete()
            return redirect('main:login')
    else:
        form = AddInfoForm(instance=user)
        context = {
            'form':form,
        }
    return render(request, 'addinfo.html', context)

# 로그아웃
def logout(request):
    auth.logout(request)
    return redirect('main:home')

# 마이페이지
@login_required
def mypage(request):
    user = request.user
    context = {
        'user':user
    }
    return render(request, 'mypage.html', context)

# 유저정보수정
@login_required
def update_user(request):
    user = request.user
    if request.method == 'POST':
        form = UserUpdateForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('main:mypage')
    else:
        form = UserUpdateForm(instance=user)    
    context = {
        'form':form
    }
    return render(request, 'update_user.html', context)

# 비밀번호변경
@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, '변경완료')
            return redirect('main:mypage')
        else:
            messages.error(request, '에러')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form':form
    }
    return render(request, 'change_password.html', context)

# 비밀번호 초기화
class UserPasswordResetView(PasswordResetView):
    template_name='registration/password_reset_form.html'
    success_url=reverse_lazy('password_reset_done')
    form_class= PasswordResetForm

    def form_valid(self, form):
        if User.objects.filter(email=self.request.POST.get("email")).exists():
            return super().form_valid(form)
        else:
            return render(self.request, 'registration/password_reset_done_fail.html')

# 회원탈퇴
def delete_user(request):
    user = request.user
    user.delete()
    auth.logout(request)
    return redirect('main:home')

#######################게시판################################
# 게시판 메인페이지
def board(request):
    board = Board.objects.all().order_by("-pub_date")
    page = int(request.GET.get('page', 1))
    paginator = Paginator(board, 7)
    page_obj = paginator.get_page(page)
    context={ 
            'page_obj':page_obj,
            'title':'게시판',
            'board':board
        }
    return render(request, 'board.html', context)

# 게시판 상세페이지
def detail(request, pk):    # pk = board_id
    board = get_object_or_404(Board, id=pk)
    reply = Reply.objects.filter(board_id=pk).order_by("-rep_date")
    page = int(request.GET.get('page', 1))
    paginator = Paginator(reply, 5)
    page_obj = paginator.get_page(page)
    context = {
        'board':board,
        'page_obj':page_obj,
        'pk':pk
    }
    return render(request, 'detail.html', context)

# 게시판 글쓰기
def write(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            temp_form = form.save(commit=False)
            temp_form.user = request.user
            temp_form.pub_date = timezone.now()
            temp_form.upload_files = request.FILES.get('upload_files')
            temp_form.save()
            return redirect('main:board')
    else:
        form = BoardForm()
    context = {
        'form':form
    }
    return render(request, 'write.html', context)
    
# 게시판에 업로드된 파일 다운로드
def download(request, pk):  # pk = board_id
    board = Board.objects.get(id=pk)
    filepath = os.path.abspath('media/')
    file_name = os.path.basename('media/'+board.upload_files.name)
    fs = FileSystemStorage(filepath)
    response = FileResponse(fs.open(file_name, 'rb'), content_type='application/download')
    response['Content-Disposition'] = 'attachment; filename=%s' % file_name
    return response

# 게시글 수정
@login_required
def update(request, pk):    # pk = board_id
    board = Board.objects.get(id=pk)
    tmp = Board.objects.get(id=pk)
    if request.method == 'POST':
        board.title = request.POST['title']
        board.content = request.POST['content']
        board.user = request.user
        board.pub_date=timezone.now()
        if request.FILES:
            if board.upload_files != "":
                os.remove(os.path.join(settings.MEDIA_ROOT, board.upload_files.path))
            board.upload_files = request.FILES.get('upload_files')
        if board.title == '':
            board.title = tmp.title
        if board.content == '':
            board.content = tmp.content
        board.save()
        return redirect('main:detail', pk)
    else:
        context = {
            'board':board,
            'pk':pk,
        }
        if board.upload_files:
            context['file_url'] = board.upload_files.url
    return render(request, 'update.html', context)        

# 게시글 삭제
@login_required
def delete(request, pk):    # pk = board_id
    board = Board.objects.get(id=pk)
    board.delete()
    return redirect('main:board')

# 게시글에 댓글작성
@login_required
def create_reply(request, pk):  # pk = board_id
    if request.method == 'POST':

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Photovle{% endblock %}</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'image/title_icon.png'%}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</head>

<body>
    <div style="display: flex;">
        <img class="logo" src="/static/image/찐로고.png" onclick="location.href='{% url "main:home" %}'">
        {% if user.is_authenticated %}
        <input type="checkbox" id="menuicon">
        <label for="menuicon">
            <span></span>
            <span></span>
            <span></span>
        </label>
        <div class="sidebar">
            <ul class="nav-links">
                <li>
                    <a style="color:#fff; cursor:default;">{{user.name}}</a>
                    <span style="cursor:default;">님 안녕하세요.</span>
                </li>
                <li>
                    <a href="{% url 'main:osvos' %}" class="link">Image Segmentation</a>        
                </li>
                <li>
                    <a href="{% url 'main:board' %}" class="link">게시판</a>        
                </li>
                <li>
                    <a href="{% url 'main:mypost' %}" class="link">나의 게시글</a>
                </li>
            </ul>        
            <ul class="nav-login">
                <li>
                    <a href="{% url 'main:mypage' %}" class="link" style="font-size: 1.2rem;">마이페이지</a>
                </li>
                <li>
                    <a href="{% url 'main:logout' %}" class="link">로그아웃</a>
                </li>
            </ul>        
        </div>
        {% else %}
        <input type="checkbox" id="menuicon">
        <label for="menuicon">
            <span></span>
            <span></span>
            <span></span>
        </label>
        <div class="sidebar">
            <ul class="nav-links">
                <li>
                    <span style="text-align:left;">로그인이 필요합니다.</span>
                </li>
                <li>
                    <a href="{% url 'main:login' %}" class="link">Image Segmentation</a>
                </li>
                <li>
                    <a href="{% url 'main:login' %}" class="link">게시판</a>
                </li>
            </ul>
            <div class="nav-login">
                <li>
                    <a href="{% url 'main:login' %}" class="link">로그인</a>
                </li>
                <li>
                    <a href="{% url 'main:signup' %}" class="link">회원가입</a>
                </li>
            </div>
        </div>
        {% endif %}
    </div>
    {% block content %}
    {% endblock %}
</body>

</html>

main/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/detail.css' %}">
<!DOCTYPE html>
<html lang="en">
   <div style="display:none">{{ board.update_counter}}</div>

<div class="container">
   
   <div class="board">
      <div class="btn-area">
         {% if board.user == user %}
            <button class="btn-design" onclick="location.href='{% url 'main:update' board.id %}'">수정</button>
            <button class="btn-design" onclick="location.href='{% url 'main:delete' board.id %}'">삭제</button>
         {% endif %}
         <button class="btn-design" onclick="location.href='{% url 'main:board' %}'">목록으로</button>
      </div>
      <ul>
         <li>
            <h2>{{ board.user }}</h2>
         </li>

         <li>
            <h2>{{ board.title }}</h2>
         </li>

         <li class="info">
            <p>{{ board.pub_date }}</p>
            <p>조회수 : {{ board.hits }}</p>
         </li>

         <li class="content">
            {{ board.content }}
         </li>

         <li>
            <div class="icon-chat">
               <img src="/static/image/icon_chat.svg" href> 
               {% if board.reply_set.count > 0 %} 
                  <p>[{{ board.reply_set.count }}]</p>
               {% endif %}
            </div>
            <div style="line-height: 30px;">
               {% if board.upload_files %}
               첨부 파일 : <a href="{% url 'main:download' pk %}">{{ board.upload_files.name }}</a>
               {% endif %}
            </div>
         </li>
            {% if user.is_authenticated %}
            <form action="{% url 'main:create_reply' board.id %}" method="post">
               {% csrf_token %}
               <ul class="board_for_read">
                  <li>
                     <input type="text" name="comment" id="comment" class="form-control" placeholder="댓글" style="width:100%">
                  </li>

                  <li>
                     <input class="btn-design" type="submit" value="추가">
                  </li>
               </ul>
            </form>
            {% endif %}
            
         <li class="reply-area">
            <div class="reply_content">
               {% if page_obj %}
                  {% for rep in page_obj %}
                     <span class="reply">{{ rep.comment }} [{{ rep.rep_date|date:'Y-m-d H:i'}}] -{{ rep.user }}</span>
                     {% if rep.user == user %}
                        <input type="button" value="수정" id="btn" onclick="document.getElementById('comment2').style.display='block'; document.getElementById('comment2').style='width:50%'; document.getElementById('update').style.display='block'; document.getElementById('btn').style.display='none'; document.getElementById('delete').style.display='none';"/>
                        <input type="button" value="삭제" id="delete" onclick="location.href='{% url 'main:delete_reply' rep.id %}';"/>
                        <form action="{% url 'main:update_reply' board.id rep.id %}" method="post">
                           {% csrf_token %}
                           <div class="form-group">
                              <input type="text" class="form-control" name="comment" id="comment2"  value="{{ rep.comment }}" style="display:none"/>
                           </div>
                           <input type="submit" value="수정완료" id=update style="display:none"/>
                        </form>
                     {% endif %}
                  {% endfor %}
               {% endif %}
            </div>
         </li>
      </ul>
      
      <!-- 페이징처리 -->
      <div id="paging">
         <ul class="pagination justify-content-center" style="margin-top: 2rem;">
            <!-- 이전페이지 -->
            {% if page_obj.has_previous %}
            <li class="page-item">
               <a class="page-link" href="./?&page=1">맨 앞으로</a>
            </li>
            <li class="page-item">
               <a class="page-link" href="./?&page={{ page_obj.previous_page_number }}">이전</a>
               <!-- href로 뎁스 설정 -->
            </li>
            {% else %}
            <li class="page-item disabled">
               <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in page_obj.paginator.page_range %}
               {% if page_number >= page_obj.number|add:-2 and page_number <= page_obj.number|add:2 %}
               <span class="{% if page_number == page_obj.number %}current{% endif %}" style="background-color: #708ae8;">
                  {% if page_number == page_obj.number %}
                     <li class="page-item active" aria-current="page">
                        <a class="page-link" href="./?&page={{ page_number }}">{{ page_number }}</a>
                     </li>
                  {% else %}
                     <a class="page-link" href="./?&page={{ page_number }}">{{ page_number }}</a>
                  {% endif %}
               </span>
               {% elif page_number >= page_obj.number|add:-3 and page_number <= page_obj.number|add:3 %}
                  ..
               {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if page_obj.has_next %}
            <li class="page-item">
               <a class="page-link" href="./?&page={{ page_obj.next_page_number }}">다음</a>
            </li>
            <li class="page-item">
               <a class="page-link" href="./?&page={{ page_obj.paginator.num_pages }}">맨 뒤로</a>
            </li>
            {% else %}
            <li class="page-item disabled">
               <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
         </ul>
      </div>
      <!-- 페이징처리 끝 -->
   </div>
</div>
{% endblock %}

main/templates/home.html
{% extends 'base_non_logo.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/home.css' %}">

{% if user.is_authenticated %}
    <input type="checkbox" id="menuicon">
    <label for="menuicon">
        <span></span>
        <span></span>
        <span></span>
    </label>
    <div class="sidebar">
        <ul class="nav-links">
            <li>
                <a style="color:#fff; cursor:default;">{{user.name}}</a>
                <span style="cursor:default;">님 안녕하세요.</span>
            </li>
            <li>
                <a href="{% url 'main:osvos' %}" class="link">Image Segmentation</a>        
            </li>
            <li>
                <a href="{% url 'main:board' %}" class="link">게시판</a>        
            </li>
            <li>
                <a href="{% url 'main:mypost' %}" class="link">나의 게시글</a>
            </li>
        </ul>        
        <ul class="nav-login">
            <li>
                <a href="{% url 'main:mypage' %}" class="link" style="font-size: 1.2rem;">마이페이지</a>
            </li>
            <li>
                <a href="{% url 'main:logout' %}" class="link">로그아웃</a>
            </li>
        </ul>        
    </div>
{% else %}
    <input type="checkbox" id="menuicon">
    <label for="menuicon">
        <span></span>
        <span></span>
        <span></span>
    </label>
    <div class="sidebar">
        <ul class="nav-links">
            <li>
                <span style="text-align:left; cursor:default;">로그인이 필요합니다.</span>
            </li>
            <li>
                <a href="{% url 'main:login' %}" class="link">Image Segmentation</a>
            </li>
            <li>
                <a href="{% url 'main:login' %}" class="link">게시판</a>
            </li>
        </ul>
        <div class="nav-login">
            <li>
                <a href="{% url 'main:login' %}" class="link">로그인</a>
            </li>
            <li>
                <a href="{% url 'main:signup' %}" class="link">회원가입</a>
            </li>
        </div>
    </div>
{% endif %}
<div class="wrapper" style="text-align: center;">
    <div class="content" style="text-align: center;">
        <img class="image" src="/static/image/찐로고.png" width="288px;">
        <h2 style="color:gray; margin-top:6px; font-size: 16px">당신의 모델 학습 데이터를 보조하겠습니다.</h2>
        <div style="margin-top:15px">
            {% if user.is_authenticated %}
                <div>
                    <button style="background-color: #708ae8; border:none;" class="btn btn-primary" onclick="location.href='{% url 'main:osvos' %}'">Image segmentation start</button>
                </div>
            {% else %}
                <div>
                    <button style="background-color: #708ae8; border:none;" class="btn btn-primary" onclick="location.href='{% url 'main:login' %}'">로그인</button>
                </div>
                <div>
                    <button style="background-color: #708ae8; border:none;" class="btn btn-primary" onclick="location.href='{% url 'main:signup' %}'">회원가입</button>
                </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base_non_logo.html' %}
{% load static %}
{% load socialaccount %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/login.css' %}">

<div class="login-body">
    <div class="float-area">
        {% include "form_errors.html" %}
    </div>
</div>
<div class="container">
    <ul  class="logo-area">
        <li>
            <img src="/static/image/photovle_logo.png" onclick="location.href='{% url 'main:home' %}'">
        </li>
        <li>
            <img src="/static/image/robot.png" alt="login form"/>
        </li>
    </ul>
    <div class="login-area">        
        <form action="{% url 'main:login' %}" method='POST'>
            {% csrf_token %}
            <ul class="login-div">
                <li>
                    <h2 class="login-title" style="cursor:default;">로그인</h2>
                    <span>이미지 레이블링 보조 작업자</span>
                </li>
                <li>
                    <div>
                        <label class="form-title" style="margin-top: 28px;">이메일</label>
                        <input type="text" id="input1" name="username" class="input-control" style="border-radius: none;"
                            value="{{ form.username.value|default_if_none:'' }}" placeholder="이메일을 입력하시오."/>
                    </div>
                </li>
                <li>
                    <div>
                        <label class="form-title" for="form2Example27">비밀번호</label>
                        <input type="password" id="input2" name="password" class="input-control" style="border-radius: none;"
                            value="{{ form.password.value|default_if_none:'' }}" placeholder="비밀번호를 입력하시오."/>
                    </div>
                </li>

                <li style="margin-top:6px;">
                    <a class="small text-muted" style="color:#708AE8; text-decoration:none;" href="{% url 'password_reset' %}">비밀번호를 잊어버리셨나요?</a>
                </li>
                <li class="login-btn">
                    <button type="submit" style="background-color: #708ae8; color:white; width:100%; " value='Login'>로그인</button>
                </li>
                <li  class="kakao-btn">
                    <img src="/static/image/kakao_login_real.png" onclick="location.href='{% url 'main:kakao_login' %}'"></a>
                </li>
                <li>
                    <div style="text-align:center">
                        <p class="mb-5 pb-lg-2" style="color: #393f81; cursor:default;margin-top:12px;">계정이 없으신가요? <a href="{% url 'main:signup' %}"
                            style="color: #393f81;">회원가입</a></p>
                        </div>
                </li>
            </ul>
        </form>
    </div>
</div>
{% endblock %}